# Clustering Early Meccan Suras discussing *sirat*
Version: 17.03.2025  
by: Thomas Jurczyk

This notebook includes:

1. An overview and exploratory data analysis of the subchapter data that should be clustered.
2. The retrieval of document embeddings for each subchapter.
3. Clustering of the documents using the retrieved embeddings.

In [1]:
# imports
import os
import pickle 
import matplotlib.pyplot as plt
import re
import pandas as pd
from mistralai import Mistral
from dotenv import load_dotenv
import psycopg2
from psycopg2 import sql
import numpy as np
import umap
from sklearn.manifold import trustworthiness
from sklearn.cluster import HDBSCAN
from typing import Optional
import requests

# Apply a style
plt.style.use('ggplot')

# Loading all env variables from .env
load_dotenv()

MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

# Loading params for DB connection to local PostgreSQL

db_params = {
    "host": "localhost",
    "port": "5432",
    "database": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USERNAME"),
    "password": os.getenv("DB_PASSWORD")
}

/home/tommy/envs/a01-clustering/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Data
The data consists of subchapters from the A01 tafsir corpus that include a discussion of early Meccan verses that mention *sirat*. The data was downloaded using the web application and is stored in the subfolder `data`.

### Tokens per subchapter
First, we count the number of tokens in each subchapter and compare the results with each other. A token is simply defined by at least one blank space separating the tokens. The tokens are not cleaned of non-Arabic characters and still include punctuation marks as well (these might in some cases count as separate tokens as well due to the way the data was collected and reconstructed).

In [ ]:
token_counter = dict()
token_counter_per_verse = dict()
for directory in os.listdir("data"):
    if os.path.isdir("data/"+directory) and not directory.startswith("."):
        file_counter = 0
        token_counter_per_verse[directory] = 0
        #print("data/"+directory)
        for filename in os.listdir("data/"+directory):
            #print(filename)
            # Create separate dict for tokens/verse distribution
            if os.path.isfile(f"data/{directory}/{filename}"):
                file_counter += 1
                with open(f"data/{directory}/{filename}", "r", encoding="utf-8") as f:
                    text = f.read()
                    tokens = re.split(r"\s+", text)
                    token_counter[filename[:-4]] = len(tokens)
                    # Increment tokens/verse counter
                    token_counter_per_verse[directory] += len(tokens)
        # Calculate average for token/verse
        token_counter_per_verse[directory] = token_counter_per_verse[directory] / file_counter

In [ ]:
df = pd.DataFrame.from_dict(token_counter, orient="index").reset_index()

In [ ]:
df.columns = ["id", "token_count"]

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df["token_count"].plot(kind="box", title="Token distribution in subchapters", color="skyblue")

plt.savefig("images/boxplot.jpg")

In [ ]:
# show outliers and exclude (Sirazi)
df_no_sirazi = df.sort_values("token_count").iloc[:-1]

In [ ]:
df_no_sirazi.describe()

In [ ]:
df_no_sirazi["token_count"].plot(kind="box", title="Token distribution in subchapters (without Sirazi)", color="skyblue")

plt.savefig("images/boxplot_no_sirazi.jpg")

### Token distribution per verse

In [ ]:
df = pd.DataFrame.from_dict(token_counter_per_verse, orient="index").reset_index()

In [ ]:
df.columns = ["sura_aya", "count"]

In [ ]:
df

In [ ]:
df.sort_values("count")

In [ ]:
ax = df.sort_values("count", ascending=False).plot(kind="bar", x="sura_aya", title="Avg. token/subchapter distribution for each verse", color="skyblue")
# Display count on top of each bar
for bar in ax.patches:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.5, round(yval, 2), ha='center', va='bottom')

plt.ylim(0,6500)
plt.ylabel("avg. tokens")

plt.tight_layout()

plt.savefig("images/token_verse_distribution.jpg")

## Embeddings
In a first step, we are acquiring the embeddings using Mistral's `mistral-embed` model.

### Full Subchapter Embeddings

We are creating three lists for the text ids, texts, and the embeddings. Some subchapters appear multiple times in the dataset, so the duplicates need to be skipped.

In [ ]:
sc_id_list = []
sc_text_list = []
sc_embeddings_list = []

In [ ]:
for directory in os.listdir("data"):
    if os.path.isdir("data/"+directory) and not directory.startswith("."):
        #print("data/"+directory)
        for filename in os.listdir("data/"+directory):
            # Create separate dict for tokens/verse distribution
            if os.path.isfile(f"data/{directory}/{filename}"):
                if filename[:-4] not in sc_id_list:
                    file_counter += 1
                    with open(f"data/{directory}/{filename}", "r", encoding="utf-8") as f:
                        text = f.read()
                        sc_id_list.append(filename[:-4])
                        sc_text_list.append(text)

In [ ]:
sc_id_list[:3]

Now, we are retrieving the embeddings for each text and store them in the respective list.  
**Important**: The embeddings are afterwards stored in a database and locally on the computer. Therefore, this step only needs to be executed when something has changed.

In [ ]:
import time

model = "mistral-embed"
execute = False
client = Mistral(api_key=MISTRAL_API_KEY)

# The max token per batch is 16384 or sometimes even lower for some reason (?)
# We split longer texts into chunks
# Using a sliding window approach with an overlap of 50 tokens
# We also need to use time.sleep() to avoid exceeding rate limits with 6 requests per sec
if execute:
    for idx, text in enumerate(sc_text_list):
        #print(f"{idx}. {sc_id_list[idx]}")
        tokens = re.split(r"\s+", text)
        if len(tokens) > 1000:
            #print(f"Text {sc_id_list[idx]} is too long: {len(tokens)}") 
            tmp_embeddings = list()
            # Splitting the text into chunks
            window_size = 500
            stride = 450 # Overlap of 50 tokens
            for start_idx in range(0,len(tokens), stride):
                end_idx = min(start_idx + window_size, len(tokens))
                tmp_text = " ".join(tokens[start_idx:end_idx])
                res = client.embeddings.create(model=model, inputs=[tmp_text])
                tmp_embeddings.append(res.data[0].embedding)
                time.sleep(0.1)
            # Calculate mean from all chunk embeddings
            sc_embeddings_list.append(np.mean(tmp_embeddings, axis=0).tolist())
        else:
            res = client.embeddings.create(model=model, inputs=[text])
            sc_embeddings_list.append(res.data[0].embedding)
            time.sleep(0.1)

In [ ]:
# Saving embeddings locally

with open("mistral_embeddings_full.pkl", "wb") as f:
    pickle.dump(sc_embeddings_list, f)

In [ ]:
# Reload embeddings
with open("mistral_embeddings_full.pkl", "rb") as f:
    loaded_embeddings = pickle.load(f)

In [ ]:
# Connecting to PostgreSQL and storing embeddings in table

In [ ]:
try:
    conn = psycopg2.connect(**db_params)
    cursor = conn.cursor()
    print("Connection to DB was successful!!")

    for idx, value in enumerate(loaded_embeddings):
        cursor.execute("""
            INSERT INTO embedding.sc_mistral_fulltext (subchapter_id, embedding) 
            VALUES (%s, %s)
        """, (sc_id_list[idx], value))
    
        # Änderungen bestätigen
        conn.commit()
    print("Data was added!")

except Exception as e:
    print(f"Error: {e}")
    if conn:
        conn.rollback()
finally:
    # Close connection
    if cursor:
        cursor.close()
    if conn:
        conn.close()
    print("DB connection closed.")

### Test embeddings for Arabic texts: MSA
We will try and cluster simple Arabic texts to see if this even works.

In [2]:
# Loading test data
df_test = pd.read_csv("arabic-test-data.csv")

In [3]:
df_test

,arabic_text,translation,category
0,صباح الخير! كيف حالك اليوم؟,Good morning! How are you today?,daily
1,أنا ذاهب إلى السوق لشراء بعض الفواكه والخضروات.,I am going to the market to buy some fruits an...,daily
2,الطقس جميل اليوم، أليس كذلك؟,"The weather is beautiful today, isn't it?",daily
3,هل يمكنك مساعدتي في العثور على الطريق إلى المحطة؟,Can you help me find the way to the station?,daily
4,أحب القراءة في وقت فراغي.,I like reading in my free time.,daily
5,التكنولوجيا تتطور بسرعة كبيرة في عصرنا الحالي.,Technology is developing rapidly in our curren...,technology
6,الذكاء الاصطناعي يغير طريقة عملنا وتفكيرنا.,Artificial intelligence is changing the way we...,technology
7,أصبحت الهواتف الذكية جزءًا لا يتجزأ من حياتنا ...,Smartphones have become an integral part of ou...,technology
8,شبكة الإنترنت تربط الناس من جميع أنحاء العالم.,The internet connects people from all over the...,technology
9,البرمجة هي لغة المستقبل.,Programming is the language of the future.,technology
10,البحر الأزرق والسماء الصافية يجعلان المشهد خلا...,The blue sea and clear sky make the scene brea...,nature
11,تعتبر الغابات المطيرة رئة الأرض.,Rainforests are considered the lungs of the Ea...,nature
12,الحفاظ على البيئة مسؤولية الجميع.,Preserving the environment is everyone's respo...,nature
13,تتميز الصحراء العربية بجمالها وقساوتها.,The Arabian desert is characterized by its bea...,nature
14,تهاجر الطيور مسافات طويلة بحثًا عن الدفء.,Birds migrate long distances in search of warmth.,nature
15,الصحة تاج على رؤوس الأصحاء لا يراه إلا المرضى.,Health is a crown on the heads of the healthy ...,health
16,ممارسة الرياضة بانتظام تقوي جهاز المناعة.,Regular exercise strengthens the immune system.,health
17,النوم الكافي ضروري للصحة النفسية والجسدية.,Adequate sleep is essential for mental and phy...,health
18,التغذية المتوازنة أساس الصحة الجيدة.,Balanced nutrition is the foundation of good h...,health
19,الوقاية خير من العلاج.,Prevention is better than cure.,health

In [4]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   arabic_text  20 non-null     object
 1   translation  20 non-null     object
 2   category     20 non-null     object
dtypes: object(3)
memory usage: 608.0+ bytes

In [5]:
text_list = df_test["arabic_text"].tolist()

In [6]:
text_list

['صباح الخير! كيف حالك اليوم؟',
 'أنا ذاهب إلى السوق لشراء بعض الفواكه والخضروات.',
 'الطقس جميل اليوم، أليس كذلك؟',
 'هل يمكنك مساعدتي في العثور على الطريق إلى المحطة؟',
 'أحب القراءة في وقت فراغي.',
 'التكنولوجيا تتطور بسرعة كبيرة في عصرنا الحالي.',
 'الذكاء الاصطناعي يغير طريقة عملنا وتفكيرنا.',
 'أصبحت الهواتف الذكية جزءًا لا يتجزأ من حياتنا اليومية.',
 'شبكة الإنترنت تربط الناس من جميع أنحاء العالم.',
 'البرمجة هي لغة المستقبل.',
 'البحر الأزرق والسماء الصافية يجعلان المشهد خلابًا.',
 'تعتبر الغابات المطيرة رئة الأرض.',
 'الحفاظ على البيئة مسؤولية الجميع.',
 'تتميز الصحراء العربية بجمالها وقساوتها.',
 'تهاجر الطيور مسافات طويلة بحثًا عن الدفء.',
 'الصحة تاج على رؤوس الأصحاء لا يراه إلا المرضى.',
 'ممارسة الرياضة بانتظام تقوي جهاز المناعة.',
 'النوم الكافي ضروري للصحة النفسية والجسدية.',
 'التغذية المتوازنة أساس الصحة الجيدة.',
 'الوقاية خير من العلاج.']

In [7]:
# Get embeddings
model = "mistral-embed"

client = Mistral(api_key=MISTRAL_API_KEY)

embeddings_batch_response = client.embeddings.create(
    model=model,
    inputs=text_list,
)

In [8]:
embeddings_test = [entry.embedding for entry in embeddings_batch_response.data]

In [9]:
embeddings_test[0][:10]

[-0.0182342529296875,
 0.03521728515625,
 0.025726318359375,
 -0.01136016845703125,
 0.039459228515625,
 0.0269622802734375,
 0.09539794921875,
 -0.052947998046875,
 -0.023468017578125,
 -0.01947021484375]

In [10]:
# Test clustering to check how useful the embeddings are

In [11]:
from sklearn.cluster import KMeans

In [12]:
umap_reducer = umap.UMAP(random_state=42)

In [13]:
emb_reduced = umap_reducer.fit_transform(embeddings_test)

/home/tommy/envs/a01-clustering/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/tommy/envs/a01-clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [20]:
# Train k-means in hope to recreate the initial five clusters
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(emb_reduced)

df_test["cluster"] = kmeans.labels_

In [21]:
df_test.to_csv("tables/kmeans_msa_test.csv")

In [ ]:
# Add embeddings to database
db_test_params = {
    "host": "localhost",
    "port": "5432",
    "database": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USERNAME"),
    "password": os.getenv("DB_PASSWORD")
}

try:
    conn = psycopg2.connect(**db_test_params)
    cursor = conn.cursor()
    print("Connection to DB was successful!!")

    for idx, row in df_test.iterrows():
        cursor.execute("""
            INSERT INTO embedding.test_embeddings (id, embedding, category, translation) 
            VALUES (%s, %s, %s, %s)
        """, (idx, embeddings_test[idx], row["category"], row["translation"]))
    
        # Änderungen bestätigen
        conn.commit()
    print("Data was added!")

except Exception as e:
    print(f"Error: {e}")
    if conn:
        conn.rollback()
finally:
    # Close connection
    if cursor:
        cursor.close()
    if conn:
        conn.close()
    print("DB connection closed.")

### Test embeddings for Arabic texts: Classical Arabic
We will try and cluster classical Arabic texts to see if this even works.

In [22]:
# Loading test data
df_test = pd.read_csv("classical-arabic-testdata.csv")

In [27]:
df_test

,ID,Category,Author,Period,Arabic_Text,English_Translation
0,1,Classical Poetry,Imru al-Qais,Pre-Islamic,قِفَا نَبْكِ مِنْ ذِكْرَى حَبِيبٍ وَمَنْزِلِ ‖...,Let us stop and weep over the memory of a belo...
1,2,Classical Poetry,Al-Mutanabbi,915-965 CE,الخَيلُ وَاللَيلُ وَالبَيداءُ تَعرِفُني ‖ وَال...,The horse the night and the desert know me ‖ A...
2,3,Classical Poetry,Abu al-Ala al-Ma'arri,973-1057 CE,أَرَانِي فِي الثَّلاثَةِ مِنْ سُجُونِي ‖ فَلا ...,I find myself in three prisons ‖ So do not ask...
3,4,Classical Poetry,Zuhair bin Abi Sulma,Pre-Islamic,وَمَن لَم يُصانِع في أُمورٍ كَثيرَةٍ ‖ يُضَرَّ...,And he who does not compromise in many matters...
4,5,Classical Poetry,Al-Khansa,7th century CE,تَبكي خِناسٌ عَلَى صَخرٍ وَحَقَّ لَها ‖ إِذ را...,Khansa weeps for Sakhr and she has the right t...
5,6,Quranic Verses,Quran,7th century CE,بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ ۝ الْحَم...,In the name of Allah the Most Gracious the Mos...
6,7,Quranic Verses,Quran,7th century CE,قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝...,"Say ""He is Allah [who is] One ۝ Allah the Eter..."
7,8,Quranic Verses,Quran,7th century CE,لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا...,Allah does not burden a soul beyond that it ca...
8,9,Quranic Verses,Quran,7th century CE,وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا ...,And hold firmly to the rope of Allah all toget...
9,10,Quranic Verses,Quran,7th century CE,وَقَضَى رَبُّكَ أَلَّا تَعْبُدُوا إِلَّا إِيَّ...,And your Lord has decreed that you not worship...
10,11,Classical Prose,Ibn al-Muqaffa,8th century CE,ليس العاقل من يعرف الخير من الشر، ولكن العاقل ...,The wise person is not one who knows good from...
11,12,Classical Prose,Al-Jahiz,776-868 CE,الكتاب وعاء ملىء علما، وظرف حشي ظرفا، وإناء شح...,A book is a vessel filled with knowledge a con...
12,13,Classical Prose,Ibn Khaldun,1332-1406 CE,إن الإنسان مدني بالطبع، أي لا بد له من الاجتما...,Man is civilized by nature meaning he must liv...
13,14,Classical Prose,Al-Hamadhani,967-1007 CE,وما أنا إلا رجل من العرب، آكل ما وجدت، وأمضي إ...,I am but a man of the Arabs I eat what I find ...
14,15,Classical Prose,Ibn Tufail,1105-1185 CE,فالحكمة هي السبيل إلى معرفة الله، ومعرفة الله ...,Wisdom is the path to knowing God and knowing ...
15,16,Wisdom & Proverbs,Ancient Arabic Proverb,Classical,الحاجة أم الاختراع,Necessity is the mother of invention
16,17,Wisdom & Proverbs,Ali ibn Abi Talib,7th century CE,قيمة كل امرئ ما يحسنه,The worth of a man is in what he masters
17,18,Wisdom & Proverbs,Ancient Arabic Proverb,Classical,إذا تم العقل نقص الكلام,When reason is complete speech becomes less
18,19,Wisdom & Proverbs,Luqman,Classical,لسانك حصانك، إن صنته صانك، وإن هنته هانك,Your tongue is your steed; if you take care of...
19,20,Wisdom & Proverbs,Ancient Arabic Proverb,Classical,عند الامتحان يكرم المرء أو يهان,At the time of testing a person is either hono...
20,21,Historical Documents,Treaty of Hudaybiyyah,628 CE,بسمك اللهم، هذا ما صالح عليه محمد بن عبد الله ...,In Your name O Allah this is what Muhammad ibn...
21,22,Historical Documents,Umar ibn al-Khattab,7th century CE,أما بعد، فإن القضاء فريضة محكمة، وسنة متبعة، ف...,To proceed: Adjudication is a decisive obligat...
22,23,Historical Documents,Ali ibn Abi Talib,7th century CE,وأشعر قلبك الرحمة للرعية، والمحبة لهم، واللطف ...,Fill your heart with mercy love and kindness t...
23,24,Historical Documents,Tariq ibn Ziyad,711 CE,أيها الناس، أين المفر؟ البحر من ورائكم، والعدو...,O people where will you flee? The sea is behin...
24,25,Historical Documents,Pledge of Aqaba,621-622 CE,بايعناك على السمع والطاعة في العسر واليسر، وال...,We pledge allegiance to you to listen and obey...
25,26,Philosophical Texts,Al-Kindi,801-873 CE,الفلسفة هي معرفة الأشياء بحقائقها بقدر طاقة ال...,Philosophy is knowledge of the reality of thin...
26,27,Philosophical Texts,Ibn Rushd,1126-1198 CE,الحق لا يضاد الحق بل يوافقه ويشهد له,Truth does not contradict truth but rather agr...
27,28,Philosophical Texts,Al-Farabi,872-950 CE,العقل في الإنسان كالشمس في العالم,Intellect in man is like the sun in the world
28,29,Philosophical Texts,Ibn Sina,980-1037 CE,إن وجود النفس لا يحتاج إلى برهان، لأنها تدرك ذ...,The existence of the soul needs no proof for i...
29,30,Philosophical Texts,Al-Ghazali,1058-1111 CE,العلم بلا عمل كالشجر بلا ثمر,Knowledge without action is like a tree withou...
30,31,Literary Narratives,Al-Hariri,1054-1122 CE,وحدثنا عيسى بن هشام قال: دفعتني المقادير إلى ص...,Isa ibn Hisham told us: Destiny drove me to Sa...
31,32,Literary Narratives,Arabian Nights,Classical,بلغني أيها الملك السعيد أنه كان في قديم الزمان...,It has reached me O fortunate King that in anc...
32,33,Literary Narratives,Ibn Zaydun,1003-1071 CE,أما بعد، فإني أكتب إليك من منزلة لو علمت بها ا...,To proceed: I write to you from a position tha...
33,34,Literary Narratives,Kalila wa Dimna,8th century CE,إن الملك إذا كان شديد الغضب قليل الأناة محتاجً...,If a king is quick to anger lacks patience and...
34,35,Literary Narratives,Al-Hamadhani,967-1007 CE,فلما انتصف الليل وهدأت العيون، سعى إلى الكيس س...,When midnight came and eyes were quieted he cr...

In [24]:
text_list = df_test["Arabic_Text"].tolist()

In [25]:
text_list[:3]

['قِفَا نَبْكِ مِنْ ذِكْرَى حَبِيبٍ وَمَنْزِلِ ‖ بِسِقْطِ اللِّوَى بَيْنَ الدَّخُولِ فَحَوْمَلِ',
 'الخَيلُ وَاللَيلُ وَالبَيداءُ تَعرِفُني ‖ وَالسَيفُ وَالرُمحُ وَالقِرطاسُ وَالقَلَمُ',
 'أَرَانِي فِي الثَّلاثَةِ مِنْ سُجُونِي ‖ فَلا تَسْأَلْ عَن الخَبَرِ النَّبِيثِ']

In [26]:
# Get embeddings
model = "mistral-embed"

client = Mistral(api_key=MISTRAL_API_KEY)

embeddings_batch_response = client.embeddings.create(
    model=model,
    inputs=text_list,
)

In [28]:
embeddings_test = [entry.embedding for entry in embeddings_batch_response.data]

In [29]:
# Test clustering to check how useful the embeddings are
from sklearn.cluster import KMeans

In [30]:
umap_reducer = umap.UMAP(random_state=42)

In [31]:
emb_reduced = umap_reducer.fit_transform(embeddings_test)

/home/tommy/envs/a01-clustering/lib/python3.10/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/tommy/envs/a01-clustering/lib/python3.10/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

In [34]:
# Train k-means in hope to recreate the initial five clusters
kmeans = KMeans(n_clusters=7, random_state=42)
kmeans.fit(emb_reduced)

df_test["cluster"] = kmeans.labels_

In [35]:
df_test.to_csv("tables/kmeans_ca_test.csv")

In [ ]:
# Add embeddings to database
db_test_params = {
    "host": "localhost",
    "port": "5432",
    "database": os.getenv("DB_NAME"),
    "user": os.getenv("DB_USERNAME"),
    "password": os.getenv("DB_PASSWORD")
}

try:
    conn = psycopg2.connect(**db_test_params)
    cursor = conn.cursor()
    print("Connection to DB was successful!!")

    for idx, row in df_test.iterrows():
        cursor.execute("""
            INSERT INTO embedding.test_embeddings_classical (id, embedding, category, translation) 
            VALUES (%s, %s, %s, %s)
        """, (idx, embeddings_test[idx], row["Category"], row["English_Translation"]))
    
        # Änderungen bestätigen
        conn.commit()
    print("Data was added!")

except Exception as e:
    print(f"Error: {e}")
    if conn:
        conn.rollback()
finally:
    # Close connection
    if cursor:
        cursor.close()
    if conn:
        conn.close()
    print("DB connection closed.")

## Dimensionality Reduction & Clustering
For easier plotting and comparison, we reduce the 1024 features from Mistral's embeddings to 2 features. We will be using umap for the dimensionality reduction.

First, we load the stored Mistral AI embeddings and the subchapter corpus.

In [ ]:
# Load embeddings
loaded_embeddings = []
with open("mistral_embeddings_full.pkl", "rb") as f:
    loaded_embeddings = pickle.load(f)

In [ ]:
# Loading texts and ids from drive
sc_dict = dict()
idx = 0
for directory in os.listdir("data"):
    if os.path.isdir("data/"+directory) and not directory.startswith("."):
        #print("data/"+directory)
        for filename in os.listdir("data/"+directory):
            # Create separate dict for tokens/verse distribution
            if os.path.isfile(f"data/{directory}/{filename}"):
                if filename[:-4] not in sc_dict:
                    sc_dict[filename[:-4]] = {"embedding": loaded_embeddings[idx]}
                    idx += 1

df = pd.DataFrame.from_dict(sc_dict, orient="index")

If we want, we can further filter the subchapter corpus, for instance by only selecting subchapters that discuss exactly one aya.

In [ ]:
df.loc["sc.18_1_1_7"]

Next, we apply umap on the np.array version of the embeddings.

In [ ]:
# First convert all lists to np.arrays, otherwise umap won't work
embeddings_orig = df["embedding"].to_numpy()
embeddings_orig = [np.array(l) for l in embeddings_orig]

In [ ]:
#umap_reducer = umap.UMAP(n_neighbors=2, 
                         #min_dist=0.1, 
                         #n_components=2,
                         #metric="cosine",
                         #random_state=42)
umap_reducer = umap.UMAP(random_state=42)

In [ ]:
embeddings_reduced = umap_reducer.fit_transform(embeddings_orig)

In [ ]:
df["reduced_embeddings"] = embeddings_reduced.tolist()

In [ ]:
df.info()

In [ ]:
df.head()

**TODO**: Evaluation of dimensionality reduction. We are using trustworthiness here.

In [ ]:
trust_score = trustworthiness(embeddings_orig, embeddings_reduced)
print(f"Trustworthiness: {trust_score}")

Next, we are using HDBSCAN to cluster the data.

In [ ]:
hdbscan_clusterer = HDBSCAN()

cluster_labels = hdbscan_clusterer.fit_predict(embeddings_reduced)

In [ ]:
# Adding cluster labels to dataframe
df["cluster"] = cluster_labels

In [ ]:
df.groupby("cluster").count().sort_values("embedding", ascending=False).to_csv("tables/cluster_overview.csv")

Plotting the results.

In [ ]:
# Plot reduced datapoints
plt.figure(figsize=(10, 8))

# Create scatter plot
scatter = plt.scatter(embeddings_reduced[:, 0], 
            embeddings_reduced[:, 1], 
            c=cluster_labels, 
            cmap='rainbow', 
            s=10, 
            alpha=0.7)

# Add a legend for the clusters
legend1 = plt.legend(*scatter.legend_elements(),
                    title="Clusters")
plt.gca().add_artist(legend1)

# Title
plt.title("HDBSCAN clustering of all subchapters")

# Saving plot
plt.savefig("images/hdbscan_all.jpg")

## Retrieving texts of subchapters in each cluster

In [ ]:
def download_subchapter_file(subchapter_id: str, filename: Optional[str] = None):
    # Build API path from sc_id
    # Example: http://localhost:8080/api/download/tafsir/3/c.3_2/sc.3_2_77_77
    url = "http://localhost:8080/api/download/tafsir/"
    sc_list = subchapter_id.split("_")
    tafsir_id = sc_list[0].split(".")[1]
    url += tafsir_id + "/"
    chapter_id = "c." + tafsir_id + "_" + sc_list[1]
    url += chapter_id + "/" + subchapter_id
    # DEBUG
    print(url)
    
    # Send request
    response = requests.get(url)
    
    # Check if request was successful
    response.raise_for_status()
    
    # Save file
    with open(filename, 'wb') as file:
        file.write(response.content)
    
    return filename

In [ ]:
def download_cluster_subchapters(subchapter_list: list[str], path: str):
        if not os.path.exists(path):
            os.makedirs(path)
            print(f"Directory created: {path}")
        else:
            print(f"Directory already exists: {path}")
        for sc in subchapter_list:
            download_subchapter_file(sc, f"{path}/{sc}.txt")

In [ ]:
#for i in df.cluster.unique():
   #download_cluster_subchapters(df[df["cluster"]==i].index.tolist(), f"clustering/{i}")

## Retrieving metadata for each subchapter in cluster

In [ ]:
def get_subchapter_metadata(sc_id: str) -> (dict, str):
    # Get tafsir id from sc id
    # This is needed since the API only delivers metadata for tafsirs, not subchapters
    # sc ids should look like this: sc.1_2_1_7 where the tafsir id is the 1 in sc.1
    try:
        tafsir_id = sc_id.split("_")[0].split(".")[1].strip()
    except:
        return dict(), f"Could not parse tafsir id from sc id {sc_id}"
    if tafsir_id == "":
        return dict(), f"Could not parse tafsir id from sc id {sc_id}"
    res = requests.get(f"http://localhost:8080/api/metadata/overview/{tafsir_id}")
    try:
        res.raise_for_status()
    except:
        return dict(), f"Could not retrieve data via API for tafsir id {tafsir_id}"
    return res.json(), ""

In [ ]:
# Save metadata for all clusters
for i in df.cluster.unique():
    data = dict()
    for idx, sc in enumerate(df[df["cluster"]==i].index.tolist()):
        json_res, err = get_subchapter_metadata(sc)
        # Adding sc id to JSON data
        json_res["sc_id"] = sc
        data[idx] = json_res
    df_metadata = pd.DataFrame.from_dict(data, orient="index")
    df_metadata = df_metadata.map(lambda x: "; ".join(x) if type(x) == list else x)
    df_metadata.to_csv(f"tables/cluster_{i}.csv")

## Re-clustering of subchapters in a specific cluster 12

In [ ]:
df[df["cluster"] == 12].info()

In [ ]:
df_cp = df[df["cluster"] == 12].copy()

In [ ]:
df_cp.info()

In [ ]:
# Reconverting embeddings to numpy arrays
tmp = df_cp["reduced_embeddings"].to_numpy()
reduced_embeddings_subcluster = np.array([list(x) for x in tmp])

In [ ]:
hdbscan_clusterer = HDBSCAN()

cluster_labels = hdbscan_clusterer.fit_predict(reduced_embeddings_subcluster)

In [ ]:
df_cp["subcluster"] = cluster_labels

In [ ]:
# Plot reduced datapoints
plt.figure(figsize=(10, 8))

# Create scatter plot
scatter = plt.scatter(reduced_embeddings_subcluster[:, 0], 
            reduced_embeddings_subcluster[:, 1], 
            c=cluster_labels, 
            cmap='rainbow', 
            s=10, 
            alpha=0.7)

# Add a legend for the clusters
legend1 = plt.legend(*scatter.legend_elements(),
                    title="Clusters")
plt.gca().add_artist(legend1)

# Title
plt.title("HDBSCAN clustering of entries in cluster 12 (Q1:6-7)")

# Saving plot
plt.savefig("images/hdbscan_subcluster_12.jpg")

In [ ]:
## Saving files
#for i in df_cp.subcluster.unique():
 #  download_cluster_subchapters(df_cp[df_cp["subcluster"]==i].index.tolist(), f"clustering/subcluster/{i}")

In [ ]:
def get_subchapter_metadata(sc_id: str) -> (dict, str):
    # Get tafsir id from sc id
    # This is needed since the API only delivers metadata for tafsirs, not subchapters
    # sc ids should look like this: sc.1_2_1_7 where the tafsir id is the 1 in sc.1
    try:
        tafsir_id = sc_id.split("_")[0].split(".")[1].strip()
    except:
        return dict(), f"Could not parse tafsir id from sc id {sc_id}"
    if tafsir_id == "":
        return dict(), f"Could not parse tafsir id from sc id {sc_id}"
    res = requests.get(f"http://localhost:8080/api/metadata/overview/{tafsir_id}")
    try:
        res.raise_for_status()
    except:
        return dict(), f"Could not retrieve data via API for tafsir id {tafsir_id}"
    return res.json(), ""

In [ ]:
# Save metadata for all clusters
#for i in df_cp.subcluster.unique():
 #   data = dict()
  #  for idx, sc in enumerate(df_cp[df_cp["subcluster"]==i].index.tolist()):
   #     json_res, err = get_subchapter_metadata(sc)
    #    # Adding sc id to JSON data
     #   json_res["sc_id"] = sc
      #  data[idx] = json_res
    #df_metadata = pd.DataFrame.from_dict(data, orient="index")
    #df_metadata = df_metadata.map(lambda x: "; ".join(x) if type(x) == list else x)
    #df_metadata.to_csv(f"tables/subcluster_{i}.csv")